### ISSUE TITLE
Unable to compute Shoreline Changes

### ISSUE THREAD

**Issue by Stratodude** [qscat/qscat#45]
Hi,

Here is the python error I get when I try to compute any (SCE, NVM, EPR, etc.) Shoreline change:

```
2024-07-02T17:18:37     WARNING    Traceback (most recent call last):
              File "C:\Users/antoi/AppData/Roaming/QGIS/QGIS3\profiles\nicolas/python/plugins\qscat\core\shoreline_change.py", line 215, in 
              lambda: self.get_transects_intersections_task_state_changed()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/antoi/AppData/Roaming/QGIS/QGIS3\profiles\nicolas/python/plugins\qscat\core\shoreline_change.py", line 280, in get_transects_intersections_task_state_changed
              self.create_summary_report(stat_values)
              File "C:\Users/antoi/AppData/Roaming/QGIS/QGIS3\profiles\nicolas/python/plugins\qscat\core\shoreline_change.py", line 301, in create_summary_report
              summary["SCE_avg"] = round(sum(SCE) / len(SCE), 2)
              ~~~~~~~~~^~~~~~~~~~
             ZeroDivisionError: division by zero
```

**To Reproduce**
Just following the tutorial steps with pretty standard data from Norway [EPSG:32633]
![image](https://github.com/qscat/qscat/assets/73172654/e5e1ecd9-9b58-44dc-b35e-b0c7cc7d89fd)

**Desktop**
QGIS 3.38
Windows

Let me know if you need further information, I will be happy to help.

Cheers

**Comment by louisfacun** [comment]
In "Transects layer", double check if you are selecting the correct transects layer.

**Comment by Stratodude** [comment]
Hi, I tried again being really careful of every inputs. Still got the ZeroDivisionError. Here is my dataset if you want to try:

[data_test.zip](https://github.com/user-attachments/files/16085448/data_test.zip)

Thanks a lot

**Comment by Stratodude** [comment]
Hi Louis, I found the issue comparing our dataset with yours. The shorelines need to be dissolved by date. With one multiline by date I can compute the shoreline change without any issue. Thank you for your help. Cheers
