### ISSUE TITLE
Issue while clicking "compute shoreline change"

### ISSUE THREAD

**Issue by kannan-ts** [qscat/qscat#85]
![image](https://github.com/user-attachments/assets/2ffa1b21-e39c-466c-820a-e41e7ef9221c)

Issue while calling the function Create Summary Report in shoreline_change.py

(I tried with more than 2 different files, same error)

**Comment by FLYBRETTANY** [comment]
same issue but anoher log, its seem an error type during de convertion of the "confidence inte". Qgis 3.28.11

I tried different values
the log:
2025-01-05T12:14:46     WARNING    Traceback (most recent call last):
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\qscat_plugin.py", line 153, in 
              lambda: compute_shoreline_change_button_clicked(self.dw)
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\tabs\shoreline_change.py", line 42, in compute_shoreline_change_button_clicked
              shoreline_change_inputs = inputs.shoreline_change()
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\inputs.py", line 95, in shoreline_change
              "confidence_interval": float(
             ValueError: could not convert string to float: '99,70'
             
2025-01-05T12:18:35     WARNING    Traceback (most recent call last):
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\qscat_plugin.py", line 153, in 
              lambda: compute_shoreline_change_button_clicked(self.dw)
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\tabs\shoreline_change.py", line 42, in compute_shoreline_change_button_clicked
              shoreline_change_inputs = inputs.shoreline_change()
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\inputs.py", line 95, in shoreline_change
              "confidence_interval": float(
             ValueError: could not convert string to float: '99,70'
             
2025-01-05T12:20:17     WARNING    Traceback (most recent call last):
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\qscat_plugin.py", line 153, in 
              lambda: compute_shoreline_change_button_clicked(self.dw)
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\tabs\shoreline_change.py", line 42, in compute_shoreline_change_button_clicked
              shoreline_change_inputs = inputs.shoreline_change()
              File "C:\Users/fabri/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\inputs.py", line 95, in shoreline_change
              "confidence_interval": float(
             ValueError: could not convert string to float: '99,00'

**Comment by FLYBRETTANY** [comment]
same thing with QGIS 3.34.14

**Comment by Khunfews** [comment]
someone help me to fix this please

TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int' 
Traceback (most recent call last):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\qscat_plugin.py", line 153, in 
    lambda: compute_shoreline_change_button_clicked(self.dw)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\tabs\shoreline_change.py", line 42, in compute_shoreline_change_button_clicked
    shoreline_change_inputs = inputs.shoreline_change()
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\inputs.py", line 98, in shoreline_change
    "epr_unc": self.epr_unc(),
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qscat\core\inputs.py", line 238, in epr_unc
    EPR_unc_numerator = newest_date_unc**2 + oldest_date_unc**2
TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.36.0-Maidenhead Maidenhead, 09951dc0

**Comment by har4507** [comment]
same issue with QGIS 3.44.2-Solothurn
